// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: smartbft/configuration.proto

package smartbft

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConfigMetadata with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConfigMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfigMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConfigMetadataMultiError,
// or nil if none found.
func (m *ConfigMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfigMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetConsenters() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConfigMetadataValidationError{
						field:  fmt.Sprintf("Consenters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConfigMetadataValidationError{
						field:  fmt.Sprintf("Consenters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConfigMetadataValidationError{
					field:  fmt.Sprintf("Consenters[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetOptions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfigMetadataValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfigMetadataValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfigMetadataValidationError{
				field:  "Options",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ConfigMetadataMultiError(errors)
	}

	return nil
}

// ConfigMetadataMultiError is an error wrapping multiple validation errors
// returned by ConfigMetadata.ValidateAll() if the designated constraints
// aren't met.
type ConfigMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfigMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfigMetadataMultiError) AllErrors() []error { return m }

// ConfigMetadataValidationError is the validation error returned by
// ConfigMetadata.Validate if the designated constraints aren't met.
type ConfigMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfigMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfigMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfigMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfigMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfigMetadataValidationError) ErrorName() string { return "ConfigMetadataValidationError" }

// Error satisfies the builtin error interface
func (e ConfigMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfigMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfigMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfigMetadataValidationError{}

// Validate checks the field values on Consenter with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Consenter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Consenter with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConsenterMultiError, or nil
// if none found.
func (m *Consenter) ValidateAll() error {
	return m.validate(true)
}

func (m *Consenter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConsenterId

	// no validation rules for Host

	// no validation rules for Port

	// no validation rules for MspId

	// no validation rules for Identity

	// no validation rules for ClientTlsCert

	// no validation rules for ServerTlsCert

	if len(errors) > 0 {
		return ConsenterMultiError(errors)
	}

	return nil
}

// ConsenterMultiError is an error wrapping multiple validation errors returned
// by Consenter.ValidateAll() if the designated constraints aren't met.
type ConsenterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsenterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsenterMultiError) AllErrors() []error { return m }

// ConsenterValidationError is the validation error returned by
// Consenter.Validate if the designated constraints aren't met.
type ConsenterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsenterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsenterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsenterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsenterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsenterValidationError) ErrorName() string { return "ConsenterValidationError" }

// Error satisfies the builtin error interface
func (e ConsenterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsenter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsenterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsenterValidationError{}

// Validate checks the field values on Options with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Options) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Options with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OptionsMultiError, or nil if none found.
func (m *Options) ValidateAll() error {
	return m.validate(true)
}

func (m *Options) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestBatchMaxCount

	// no validation rules for RequestBatchMaxBytes

	// no validation rules for RequestBatchMaxInterval

	// no validation rules for IncomingMessageBufferSize

	// no validation rules for RequestPoolSize

	// no validation rules for RequestForwardTimeout

	// no validation rules for RequestComplainTimeout

	// no validation rules for RequestAutoRemoveTimeout

	// no validation rules for ViewChangeResendInterval

	// no validation rules for ViewChangeTimeout

	// no validation rules for LeaderHeartbeatTimeout

	// no validation rules for LeaderHeartbeatCount

	// no validation rules for CollectTimeout

	// no validation rules for SyncOnStart

	// no validation rules for SpeedUpViewChange

	if len(errors) > 0 {
		return OptionsMultiError(errors)
	}

	return nil
}

// OptionsMultiError is an error wrapping multiple validation errors returned
// by Options.ValidateAll() if the designated constraints aren't met.
type OptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OptionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OptionsMultiError) AllErrors() []error { return m }

// OptionsValidationError is the validation error returned by Options.Validate
// if the designated constraints aren't met.
type OptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OptionsValidationError) ErrorName() string { return "OptionsValidationError" }

// Error satisfies the builtin error interface
func (e OptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OptionsValidationError{}
