// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: smartbft/common/common.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BFTMetadata with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BFTMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BFTMetadata with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BFTMetadataMultiError, or
// nil if none found.
func (m *BFTMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *BFTMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	for idx, item := range m.GetSignatures() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BFTMetadataValidationError{
						field:  fmt.Sprintf("Signatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BFTMetadataValidationError{
						field:  fmt.Sprintf("Signatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BFTMetadataValidationError{
					field:  fmt.Sprintf("Signatures[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BFTMetadataMultiError(errors)
	}

	return nil
}

// BFTMetadataMultiError is an error wrapping multiple validation errors
// returned by BFTMetadata.ValidateAll() if the designated constraints aren't met.
type BFTMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BFTMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BFTMetadataMultiError) AllErrors() []error { return m }

// BFTMetadataValidationError is the validation error returned by
// BFTMetadata.Validate if the designated constraints aren't met.
type BFTMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BFTMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BFTMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BFTMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BFTMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BFTMetadataValidationError) ErrorName() string { return "BFTMetadataValidationError" }

// Error satisfies the builtin error interface
func (e BFTMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBFTMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BFTMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BFTMetadataValidationError{}

// Validate checks the field values on BFTMetadataSignature with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BFTMetadataSignature) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BFTMetadataSignature with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BFTMetadataSignatureMultiError, or nil if none found.
func (m *BFTMetadataSignature) ValidateAll() error {
	return m.validate(true)
}

func (m *BFTMetadataSignature) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SignatureHeader

	// no validation rules for Signature

	// no validation rules for SignerId

	// no validation rules for Nonce

	if len(errors) > 0 {
		return BFTMetadataSignatureMultiError(errors)
	}

	return nil
}

// BFTMetadataSignatureMultiError is an error wrapping multiple validation
// errors returned by BFTMetadataSignature.ValidateAll() if the designated
// constraints aren't met.
type BFTMetadataSignatureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BFTMetadataSignatureMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BFTMetadataSignatureMultiError) AllErrors() []error { return m }

// BFTMetadataSignatureValidationError is the validation error returned by
// BFTMetadataSignature.Validate if the designated constraints aren't met.
type BFTMetadataSignatureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BFTMetadataSignatureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BFTMetadataSignatureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BFTMetadataSignatureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BFTMetadataSignatureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BFTMetadataSignatureValidationError) ErrorName() string {
	return "BFTMetadataSignatureValidationError"
}

// Error satisfies the builtin error interface
func (e BFTMetadataSignatureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBFTMetadataSignature.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BFTMetadataSignatureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BFTMetadataSignatureValidationError{}
