// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package smartbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "smartbft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	ConsenterId          uint64   `protobuf:"varint,1,opt,name=consenter_id,json=consenterId,proto3" json:"consenter_id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MspId                string   `protobuf:"bytes,4,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	Identity             []byte   `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,6,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,7,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetConsenterId() uint64 {
	if m != nil {
		return m.ConsenterId
	}
	return 0
}

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetMspId() string {
	if m != nil {
		return m.MspId
	}
	return ""
}

func (m *Consenter) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Options to be specified for all the smartbft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	RequestBatchMaxCount      uint64   `protobuf:"varint,2,opt,name=request_batch_max_count,json=requestBatchMaxCount,proto3" json:"request_batch_max_count,omitempty"`
	RequestBatchMaxBytes      uint64   `protobuf:"varint,3,opt,name=request_batch_max_bytes,json=requestBatchMaxBytes,proto3" json:"request_batch_max_bytes,omitempty"`
	RequestBatchMaxInterval   string   `protobuf:"bytes,4,opt,name=request_batch_max_interval,json=requestBatchMaxInterval,proto3" json:"request_batch_max_interval,omitempty"`
	IncomingMessageBufferSize uint64   `protobuf:"varint,5,opt,name=incoming_message_buffer_size,json=incomingMessageBufferSize,proto3" json:"incoming_message_buffer_size,omitempty"`
	RequestPoolSize           uint64   `protobuf:"varint,6,opt,name=request_pool_size,json=requestPoolSize,proto3" json:"request_pool_size,omitempty"`
	RequestForwardTimeout     string   `protobuf:"bytes,7,opt,name=request_forward_timeout,json=requestForwardTimeout,proto3" json:"request_forward_timeout,omitempty"`
	RequestComplainTimeout    string   `protobuf:"bytes,8,opt,name=request_complain_timeout,json=requestComplainTimeout,proto3" json:"request_complain_timeout,omitempty"`
	RequestAutoRemoveTimeout  string   `protobuf:"bytes,9,opt,name=request_auto_remove_timeout,json=requestAutoRemoveTimeout,proto3" json:"request_auto_remove_timeout,omitempty"`
	ViewChangeResendInterval  string   `protobuf:"bytes,10,opt,name=view_change_resend_interval,json=viewChangeResendInterval,proto3" json:"view_change_resend_interval,omitempty"`
	ViewChangeTimeout         string   `protobuf:"bytes,11,opt,name=view_change_timeout,json=viewChangeTimeout,proto3" json:"view_change_timeout,omitempty"`
	LeaderHeartbeatTimeout    string   `protobuf:"bytes,12,opt,name=leader_heartbeat_timeout,json=leaderHeartbeatTimeout,proto3" json:"leader_heartbeat_timeout,omitempty"`
	LeaderHeartbeatCount      uint64   `protobuf:"varint,13,opt,name=leader_heartbeat_count,json=leaderHeartbeatCount,proto3" json:"leader_heartbeat_count,omitempty"`
	CollectTimeout            string   `protobuf:"bytes,14,opt,name=collect_timeout,json=collectTimeout,proto3" json:"collect_timeout,omitempty"`
	SyncOnStart               bool     `protobuf:"varint,15,opt,name=sync_on_start,json=syncOnStart,proto3" json:"sync_on_start,omitempty"`
	SpeedUpViewChange         bool     `protobuf:"varint,16,opt,name=speed_up_view_change,json=speedUpViewChange,proto3" json:"speed_up_view_change,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetRequestBatchMaxCount() uint64 {
	if m != nil {
		return m.RequestBatchMaxCount
	}
	return 0
}

func (m *Options) GetRequestBatchMaxBytes() uint64 {
	if m != nil {
		return m.RequestBatchMaxBytes
	}
	return 0
}

func (m *Options) GetRequestBatchMaxInterval() string {
	if m != nil {
		return m.RequestBatchMaxInterval
	}
	return ""
}

func (m *Options) GetIncomingMessageBufferSize() uint64 {
	if m != nil {
		return m.IncomingMessageBufferSize
	}
	return 0
}

func (m *Options) GetRequestPoolSize() uint64 {
	if m != nil {
		return m.RequestPoolSize
	}
	return 0
}

func (m *Options) GetRequestForwardTimeout() string {
	if m != nil {
		return m.RequestForwardTimeout
	}
	return ""
}

func (m *Options) GetRequestComplainTimeout() string {
	if m != nil {
		return m.RequestComplainTimeout
	}
	return ""
}

func (m *Options) GetRequestAutoRemoveTimeout() string {
	if m != nil {
		return m.RequestAutoRemoveTimeout
	}
	return ""
}

func (m *Options) GetViewChangeResendInterval() string {
	if m != nil {
		return m.ViewChangeResendInterval
	}
	return ""
}

func (m *Options) GetViewChangeTimeout() string {
	if m != nil {
		return m.ViewChangeTimeout
	}
	return ""
}

func (m *Options) GetLeaderHeartbeatTimeout() string {
	if m != nil {
		return m.LeaderHeartbeatTimeout
	}
	return ""
}

func (m *Options) GetLeaderHeartbeatCount() uint64 {
	if m != nil {
		return m.LeaderHeartbeatCount
	}
	return 0
}

func (m *Options) GetCollectTimeout() string {
	if m != nil {
		return m.CollectTimeout
	}
	return ""
}

func (m *Options) GetSyncOnStart() bool {
	if m != nil {
		return m.SyncOnStart
	}
	return false
}

func (m *Options) GetSpeedUpViewChange() bool {
	if m != nil {
		return m.SpeedUpViewChange
	}
	return false
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "smartbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "smartbft.Consenter")
	proto.RegisterType((*Options)(nil), "smartbft.Options")
}

func init() { proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab) }

var fileDescriptor_415c9e57263f32ab = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdf, 0x6a, 0x1b, 0x39,
	0x14, 0x87, 0x99, 0xc4, 0x71, 0x6c, 0x39, 0x8e, 0x63, 0xe5, 0xdf, 0x6c, 0x76, 0x2f, 0xbc, 0xbe,
	0xd8, 0x35, 0xbb, 0x30, 0x86, 0x64, 0xb7, 0x14, 0x4a, 0x29, 0xb5, 0xa1, 0x34, 0x85, 0x90, 0x32,
	0x49, 0x7b, 0xd1, 0x1b, 0xa1, 0xd1, 0x1c, 0xdb, 0xa2, 0x33, 0xd2, 0x54, 0xd2, 0xd8, 0x71, 0xde,
	0xad, 0x0f, 0xd2, 0xb7, 0x29, 0x23, 0xcd, 0x8c, 0x4d, 0xd2, 0xbb, 0xf1, 0xf9, 0x7d, 0xdf, 0x11,
	0xe7, 0x20, 0x0b, 0x1d, 0x33, 0x29, 0x66, 0x7c, 0x9e, 0x2b, 0x6a, 0xb8, 0x14, 0x41, 0xa6, 0xa4,
	0x91, 0xb8, 0xa5, 0x53, 0xaa, 0x4c, 0x34, 0x33, 0x43, 0x85, 0x0e, 0xa7, 0x16, 0xb8, 0x01, 0x43,
	0x63, 0x6a, 0x28, 0xbe, 0x42, 0x88, 0x49, 0xa1, 0x41, 0x18, 0x50, 0xda, 0xf7, 0x06, 0xbb, 0xa3,
	0xce, 0xe5, 0x71, 0x50, 0x09, 0xc1, 0xb4, 0xca, 0xc2, 0x2d, 0x0c, 0xff, 0x8b, 0xf6, 0x65, 0x56,
	0x1c, 0xa0, 0xfd, 0x9d, 0x81, 0x37, 0xea, 0x5c, 0xf6, 0x37, 0xc6, 0xad, 0x0b, 0xc2, 0x8a, 0x18,
	0xfe, 0xf0, 0x50, 0xbb, 0x6e, 0x83, 0xff, 0x44, 0x07, 0x75, 0x23, 0xc2, 0x63, 0xdf, 0x1b, 0x78,
	0xa3, 0x46, 0xd8, 0xa9, 0x6b, 0xd7, 0x31, 0xc6, 0xa8, 0xb1, 0x90, 0xda, 0xd8, 0xd6, 0xed, 0xd0,
	0x7e, 0x17, 0xb5, 0x4c, 0x2a, 0xe3, 0xef, 0x0e, 0xbc, 0x51, 0x37, 0xb4, 0xdf, 0xf8, 0x14, 0x35,
	0x53, 0x9d, 0x15, 0x4d, 0x1a, 0x96, 0xdc, 0x4b, 0x75, 0x76, 0x1d, 0xe3, 0x0b, 0xd4, 0xe2, 0x31,
	0x08, 0xc3, 0xcd, 0xda, 0xdf, 0x1b, 0x78, 0xa3, 0x83, 0xb0, 0xfe, 0x8d, 0xff, 0x42, 0x3d, 0x96,
	0x70, 0x10, 0x86, 0x98, 0x44, 0x13, 0x06, 0xca, 0xf8, 0x4d, 0x8b, 0x74, 0x5d, 0xf9, 0x3e, 0xd1,
	0x53, 0x50, 0xa6, 0xe0, 0x34, 0xa8, 0x25, 0xa8, 0x0d, 0xb7, 0xef, 0x38, 0x57, 0x2e, 0xb9, 0xe1,
	0xf7, 0x26, 0xda, 0x2f, 0x07, 0xc6, 0xff, 0xa3, 0x73, 0x05, 0xdf, 0x72, 0xd0, 0x86, 0x44, 0xd4,
	0xb0, 0x05, 0x49, 0xe9, 0x03, 0x61, 0x32, 0x17, 0x6e, 0x92, 0x46, 0x78, 0x52, 0xc6, 0x93, 0x22,
	0xbd, 0xa1, 0x0f, 0xd3, 0x22, 0xfb, 0xb5, 0x16, 0xad, 0x0d, 0x68, 0x3b, 0xec, 0x73, 0x6d, 0x52,
	0x64, 0xf8, 0x15, 0xba, 0x78, 0xae, 0xf1, 0x62, 0x83, 0x4b, 0x9a, 0x94, 0x0b, 0x39, 0x7f, 0x62,
	0x5e, 0x97, 0x31, 0x7e, 0x83, 0xfe, 0xe0, 0x82, 0xc9, 0x94, 0x8b, 0x39, 0x49, 0x41, 0x6b, 0x3a,
	0x07, 0x12, 0xe5, 0xb3, 0x19, 0x28, 0xa2, 0xf9, 0x23, 0xd8, 0xb5, 0x35, 0xc2, 0xdf, 0x2a, 0xe6,
	0xc6, 0x21, 0x13, 0x4b, 0xdc, 0xf1, 0x47, 0xc0, 0xff, 0xa0, 0x7e, 0x75, 0x7a, 0x26, 0x65, 0xe2,
	0xac, 0xa6, 0xb5, 0x7a, 0x65, 0xf0, 0x51, 0xca, 0xc4, 0xb2, 0x2f, 0x36, 0x03, 0xce, 0xa4, 0x5a,
	0x51, 0x15, 0x13, 0xc3, 0x53, 0x90, 0xb9, 0xdb, 0x69, 0x3b, 0x3c, 0x2d, 0xe3, 0x77, 0x2e, 0xbd,
	0x77, 0x21, 0x7e, 0x89, 0xfc, 0xca, 0x63, 0x32, 0xcd, 0x12, 0xca, 0x45, 0x2d, 0xb6, 0xac, 0x78,
	0x56, 0xe6, 0xd3, 0x32, 0xae, 0xcc, 0xd7, 0xe8, 0xf7, 0xca, 0xa4, 0xb9, 0x91, 0x44, 0x41, 0x2a,
	0x97, 0x50, 0xcb, 0x6d, 0x2b, 0x57, 0xcd, 0xdf, 0xe6, 0x46, 0x86, 0x16, 0xd8, 0xd2, 0x97, 0x1c,
	0x56, 0x84, 0x2d, 0xa8, 0x98, 0x03, 0x51, 0xa0, 0x41, 0xc4, 0x9b, 0xdd, 0x22, 0xa7, 0x17, 0xc8,
	0xd4, 0x12, 0xa1, 0x05, 0xea, 0xe5, 0x06, 0xe8, 0x78, 0x5b, 0xaf, 0x4e, 0xed, 0x58, 0xad, 0xbf,
	0xd1, 0xb6, 0xe6, 0x4c, 0x80, 0xc6, 0xa0, 0xc8, 0x02, 0x8a, 0xff, 0x10, 0x50, 0x53, 0x4b, 0x07,
	0x6e, 0x4e, 0x97, 0xbf, 0xaf, 0xe2, 0xca, 0xfc, 0x0f, 0x9d, 0x3d, 0x33, 0xdd, 0x85, 0xeb, 0xba,
	0x9b, 0xf3, 0xc4, 0x73, 0x17, 0xee, 0x6f, 0xd4, 0x63, 0x32, 0x49, 0x80, 0x6d, 0x8e, 0x39, 0xb4,
	0xc7, 0x1c, 0x96, 0xe5, 0xaa, 0xfd, 0x10, 0x75, 0xf5, 0x5a, 0x30, 0x22, 0x05, 0xd1, 0x86, 0x2a,
	0xe3, 0xf7, 0x06, 0xde, 0xa8, 0x15, 0x76, 0x8a, 0xe2, 0xad, 0xb8, 0x2b, 0x4a, 0x78, 0x8c, 0x4e,
	0x74, 0x06, 0x10, 0x93, 0x3c, 0x23, 0x5b, 0x53, 0xfb, 0x47, 0x16, 0xed, 0xdb, 0xec, 0x53, 0xf6,
	0xb9, 0x1e, 0xfa, 0x43, 0xa3, 0xe5, 0x1d, 0xed, 0x84, 0x4d, 0xf7, 0x4c, 0x4d, 0x62, 0x14, 0x48,
	0x35, 0x0f, 0x16, 0xeb, 0x0c, 0x54, 0x02, 0xf1, 0x1c, 0x54, 0x30, 0xa3, 0x91, 0xe2, 0xcc, 0xbd,
	0x5c, 0x3a, 0x90, 0x2a, 0x06, 0x05, 0xaa, 0x7e, 0x5e, 0xbe, 0x5c, 0xce, 0xb9, 0x59, 0xe4, 0x51,
	0xc0, 0x64, 0x3a, 0x16, 0xb0, 0xe2, 0x66, 0x3d, 0x66, 0x8a, 0xae, 0x12, 0x50, 0xe3, 0x28, 0x91,
	0xec, 0x6b, 0xc2, 0xa3, 0x71, 0x05, 0x8f, 0x99, 0x4c, 0x53, 0x29, 0xa2, 0xa6, 0x6d, 0x76, 0xf5,
	0x33, 0x00, 0x00, 0xff, 0xff, 0x00, 0x81, 0xfc, 0xfc, 0x1d, 0x05, 0x00, 0x00,
}
